### ISSUE TITLE
PHPMailer error

### ISSUE THREAD

**Issue by thboss** [kaushikbhat07/restaurant-order-website#1]
Hi! First, let me thank you for this great project

I get the error message `Could not send verification email. Please check your internet connection.` when registering a new customer my PHP version 7.2.24

can you help, please?

**Comment by kaushikbhat07** [comment]
Hi, 
In the **includes/config.ini**, set your gmail ID and password.
And in your gmail account, [turn on less secure apps option](https://hotter.io/docs/email-accounts/secure-app-gmail/)

**Comment by thboss** [comment]
Hi, thanks for your response
So do I need to create a workspace account first?
anyway, does the PHPMailer in your project compatible with PHP 7.2?

Edit: I test as mailbox user but still get the error.

**Comment by thboss** [comment]
nvm, I create a new Gmail account and it's working now!

**Comment by kaushikbhat07** [comment]
> So do I need to create a workspace account first?

No, Follow the instructions under "Turning on 'less secure apps' settings as mailbox user" [here](https://hotter.io/docs/email-accounts/secure-app-gmail/).

> anyway, does the PHPMailer in your project compatible with PHP 7.2?

The project was developed with PHP 7. It's better to go with the same.

**Comment by thboss** [comment]
Awesome! Everything works for me (except payment) 💯 
Thank you ❤️

**Comment by genesisoliva** [comment]
> nvm, I create a new Gmail account and it's working now!

Hello, can you help me setup the email part?
