### ISSUE TITLE
Database couldnt connect

### ISSUE THREAD

**Issue by horjustin** [kaushikbhat07/restaurant-order-website#5]
![20210508_134730](https://user-images.githubusercontent.com/83641588/117528291-07135f80-b004-11eb-866c-4a926f828d6e.jpg)
Hi, which sql file do I upload as it shows that it couldn't connect to database. What do i name the database when I created a new one on pHpadmin

**Comment by kaushikbhat07** [comment]
I suggest you go with [swadesh - Schema Only.sql](https://github.com/kaushikbhat07/restaurant-order-website/blob/master/Database%20File/swadesh%20-%20Schema%20Only.sql) if you need only the tables without the data. And if you need the tables with the data, go with [swadesh - Full Data Set.sql](https://github.com/kaushikbhat07/restaurant-order-website/blob/master/Database%20File/swadesh%20-%20Full%20Data%20Set.sql).

The default database name is "swadesh". But you can keep it with any name. In case you choose to keep a different database name, make sure to update the "dbn" value in includes/config.ini, admin/includes/config.ini, staff/includes/config.ini.

**Comment by horjustin** [comment]
Thank you so much for replying and thank you for posting this wonderful project!
